[tool.poetry]
name = "data-science"
version = "0.1.0"
description = ""
authors = ["Tomasz Szpak <tomszp@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^2.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
